#  db:
FROM docker.io/postgres:12-alpine
#    restart: unless-stopped
#    environment:
#      - POSTGRES_USER=${TTRSS_DB_USER}
#      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
#      - POSTGRES_DB=${TTRSS_DB_NAME}
#    volumes:
#      - db:/var/lib/postgresql/data
#
#volumes:
#  db:
#  app:
#  certs:
#  backups:
