#  app:
FROM docker.io/cthulhoo/ttrss-fpm-pgsql-static:latest
# FROM cthulhoo/ttrss-fpm-pgsql-static:latest
#    registry.fedoraproject.org/cthulhoo/ttrss-fpm-pgsql-static:latest
#    registry.access.redhat.com/cthulhoo/ttrss-fpm-pgsql-static:latest
#  ▸ docker.io/cthulhoo/ttrss-fpm-pgsql-static:latest
#    quay.io/cthulhoo/ttrss-fpm-pgsql-static:latest

#    restart: unless-stopped
#    env_file:
#      - .env
#    volumes:
#      - app:/var/www/html
#      - ./config.d:/opt/tt-rss/config.d:ro
#    depends_on:
#      - db
